# Generated by Django 4.2.6 on 2023-11-09 18:54

import attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendance_record_date_alter_classimage_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_record',
            name='roll_no',
        ),
        migrations.AddField(
            model_name='attendance_record',
            name='course',
            field=models.CharField(blank=True, choices=[('None', 'Select'), ('MA 205', 'MA 205'), ('CS 201', 'CS 201'), ('CS 203', 'CS 203'), ('CS 207', 'CS 207')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attendance_record',
            name='department',
            field=models.CharField(blank=True, choices=[('None', 'Select'), ('CSE', 'Computer Science Engineering'), ('MnC', 'Mathematics and Computing Science Engineering'), ('EE', 'Electrical Engineering'), ('SE', 'Space Science Engineering'), ('EP', 'Engineering Physics'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('ChE', 'Chemical Engineering'), ('MEMS', 'Metallurgical and Material Science Engineering')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendance_record',
            name='year',
            field=models.CharField(blank=True, choices=[('None', 'Select'), ('B.Tech I', 'B.Tech I'), ('B.Tech II', 'B.Tech II'), ('B.Tech III', 'B.Tech III'), ('B.Tech IV', 'B.Tech IV'), ('M.Tech I', 'M.Tech I'), ('M.Tech II', 'M.Tech II')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_record',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='classimage',
            name='image',
            field=models.ImageField(upload_to=attendance.models.upload_photo),
        ),
    ]
