# Generated by Django 4.2.6 on 2023-11-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_remove_attendance_record_roll_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classimage',
            name='course',
            field=models.CharField(choices=[('None', 'Select'), ('MA 205', 'MA 205'), ('CS 201', 'CS 201'), ('CS 203', 'CS 203'), ('CS 207', 'CS 207')], default='CS 203', max_length=20),
        ),
    ]
